# Generated by Django 2.1 on 2018-08-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_auto_20180826_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='url',
            field=models.URLField(db_index=True, max_length=500),
        ),
    ]
